steps:
#Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$PROJECT_NAME','.']
#Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
 args: ['push','gcr.io/$PROJECT_ID/$PROJECT_NAME']
#Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  arg: ['run','deploy',"$Project_NAME",'--image','gcr.io/$PROJECT_ID/$PROJECT_NAME','--region','us-central1','--p']
images:
- gcr.io/$PROJECT_ID/$PROJECT_NAME